### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by jaspreet-singh-sahota**
Apple clone (Building-with-Backgrounds-and-Gradient)

This project is clone the website of one of the most design-forward companies in the world. It’s not a very complex site but it uses background photos well and the Nav-bar at the top contains a gradient that you should be able to mimic.

### CODE REVIEW

**Comment by izaiasneto4** [comment]
#### Hi @jaspreet-singh-sahota :wave: . Let's do this in order to get your pull request reviewed :arrow_down: 

- [x] Your pull request needs to have a meaningful title and a short description

When finished, please re-submit your pull request to be reviewed. :pray:

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @jaspreet-singh-sahota , 👋 kudos for readme and project implementation 👏 

- There is some element creating horizontal scroll, fix that
image

- gitignore node_modules which is not necessary 

----
#### Don't forgot to request for another code review
----

**Pon Muthu Selvam N**
_If you have any queries feel free ping me on slack_

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi Jaspreet Singh,
Good job so far, but here are few issues we need to address to get this project approved.
The last issued raised in the previous review still persist.🙂
* [x] let get rid of the horizontal review on the page. 🙂
> Give each of the images in the```. thumbnails```class a width of 25% 
Screenshot from 2019-12-10 12-42-30

* [x] It contains four elements which are links.🙂
> images in the thumbnail class must be wrapped around ```<a>```🙂
#### [OPTIONAL]
- Do not leave your alt attribute of image tags blank.🙂
## That is it Jaspreet Singh, kindly make these changes and submit for review🙂
feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you
#### Happy coding 🙂
Addo Boakye Forison

**Review by mosesogwo — APPROVED** [review]
### Hi @jaspreet-singh-sahota,

### Good job :+1: 

Your project is approved! You may now merge to master and submit a project completion form. :smile: 

### Status: Approved.

**Pull request merged**
